"""Binance Spot testnet REST driver for ADR-008 emergency flatten.

The public ``ExchangeClient`` protocol in ``emergency_flatten`` is
synchronous and intentionally small: list open orders, cancel one order,
infer spot inventory, submit a market close, query an order, and snapshot the
account. This module provides the Phase 3c-b Binance Spot testnet
implementation of that surface.

Only testnet endpoints and Ed25519 credentials are supported. The full API key
and private key are kept in memory, used only for request signing, and never
included in return values or exceptions generated by this module.
"""

from __future__ import annotations

import json
import os
import time
import urllib.error
import urllib.parse
import urllib.request
from collections.abc import Callable, Mapping, Sequence
from dataclasses import dataclass, field
from datetime import UTC, datetime
from decimal import Decimal, InvalidOperation
from typing import Any

from nautilus_trader.adapters.binance.common.credentials import (
    extract_ed25519_private_key,
    is_ed25519_private_key,
)
from nautilus_trader.core.nautilus_pyo3 import ed25519_signature

from apps.strategies_nautilus.runners.emergency_flatten import (
    AccountBalance,
    AccountSnapshot,
    EmergencyFlattenSettings,
    FlattenValidationError,
    OpenOrder,
    OpenPosition,
    OrderSnapshot,
)
from apps.strategies_nautilus.runners.testnet_runner import (
    KEY_ENV,
    MIN_CREDENTIAL_LENGTH,
    SECRET_ENV,
)

DEFAULT_BINANCE_SPOT_TESTNET_BASE_URL = "https://testnet.binance.vision"
DEFAULT_RECV_WINDOW_MS = 5000
DEFAULT_TIMEOUT_SECONDS = 10.0
DEFAULT_ACCOUNT_ID = "BINANCE-SPOT-master"
BINANCE_VENUE_SUFFIX = ".BINANCE"
TERMINAL_CANCEL_STATUSES = frozenset({"CANCELED", "EXPIRED", "FILLED"})


class BinanceSpotTestnetError(RuntimeError):
    """Base error raised by the Binance Spot testnet emergency driver."""


class BinanceSpotTestnetRestError(BinanceSpotTestnetError):
    """Raised for non-2xx Binance REST responses."""

    def __init__(
        self,
        *,
        status_code: int,
        code: int | None,
        msg: str,
    ) -> None:
        self.status_code = status_code
        self.code = code
        self.msg = msg
        super().__init__(f"binance_testnet_rest_error:{status_code}:{code}:{msg}")


@dataclass(frozen=True)
class BinanceSpotTestnetCredentials:
    api_key: str = field(repr=False)
    api_secret: str = field(repr=False)
    credentials_source: str
    credentials_key_prefix: str

    @classmethod
    def from_env(
        cls, env: Mapping[str, str] | None = None
    ) -> BinanceSpotTestnetCredentials:
        source = env if env is not None else os.environ
        api_key = source.get(KEY_ENV, "")
        api_secret = source.get(SECRET_ENV, "")
        if not api_key or not api_secret:
            raise FlattenValidationError(
                "missing_testnet_credentials",
                f"{KEY_ENV} and {SECRET_ENV} must both be set",
            )
        if len(api_key) < MIN_CREDENTIAL_LENGTH:
            raise FlattenValidationError(
                "api_key_too_short",
                f"{KEY_ENV} must be at least {MIN_CREDENTIAL_LENGTH} characters",
            )
        if len(api_secret) < MIN_CREDENTIAL_LENGTH:
            raise FlattenValidationError(
                "api_secret_too_short",
                f"{SECRET_ENV} must be at least {MIN_CREDENTIAL_LENGTH} characters",
            )
        if not is_ed25519_private_key(api_secret):
            raise FlattenValidationError(
                "ed25519_credentials_required",
                "Binance Spot testnet emergency flatten requires an Ed25519 "
                f"private key in {SECRET_ENV}",
            )
        return cls(
            api_key=api_key,
            api_secret=api_secret,
            credentials_source=f"env:{KEY_ENV},{SECRET_ENV}",
            credentials_key_prefix=api_key[:8],
        )


@dataclass(frozen=True)
class BinanceSpotTestnetConfig:
    base_url: str = DEFAULT_BINANCE_SPOT_TESTNET_BASE_URL
    recv_window_ms: int = DEFAULT_RECV_WINDOW_MS
    timeout_seconds: float = DEFAULT_TIMEOUT_SECONDS
    account_id: str = DEFAULT_ACCOUNT_ID

    def __post_init__(self) -> None:
        if self.base_url != DEFAULT_BINANCE_SPOT_TESTNET_BASE_URL:
            raise FlattenValidationError(
                "non_testnet_endpoint_rejected",
                "emergency flatten only supports Binance Spot testnet endpoint",
            )
        if self.recv_window_ms <= 0 or self.recv_window_ms > 60000:
            raise FlattenValidationError(
                "invalid_recv_window",
                "--recvWindow must be in (0, 60000] milliseconds",
            )
        if self.timeout_seconds <= 0:
            raise FlattenValidationError(
                "invalid_timeout",
                "HTTP timeout must be positive",
            )


JsonTransport = Callable[
    [str, str, Mapping[str, str], bytes | None, float],
    Any,
]
ClockMsFn = Callable[[], int]


class BinanceSpotTestnetExchangeClient:
    """Synchronous Binance Spot testnet ``ExchangeClient`` implementation."""

    def __init__(
        self,
        *,
        credentials: BinanceSpotTestnetCredentials,
        config: BinanceSpotTestnetConfig | None = None,
        transport: JsonTransport | None = None,
        clock_ms: ClockMsFn | None = None,
    ) -> None:
        self._credentials = credentials
        self._config = config or BinanceSpotTestnetConfig()
        self._transport = transport or _urllib_json_transport
        self._clock_ms = clock_ms or _system_clock_ms
        self._ed25519_key = extract_ed25519_private_key(credentials.api_secret)
        self._symbol_assets: dict[str, tuple[str, str]] = {}

    @property
    def credentials_key_prefix(self) -> str:
        return self._credentials.credentials_key_prefix

    def list_open_orders(self, instrument_id: str) -> Sequence[OpenOrder]:
        symbol = _instrument_to_symbol(instrument_id)
        payload = self._signed_request(
            "GET",
            "/api/v3/openOrders",
            {"symbol": symbol},
        )
        if not isinstance(payload, list):
            raise BinanceSpotTestnetError("openOrders response was not a list")
        return tuple(_open_order_from_payload(instrument_id, row) for row in payload)

    def cancel_order(self, *, order_id: str, instrument_id: str) -> bool:
        symbol = _instrument_to_symbol(instrument_id)
        payload = self._signed_request(
            "DELETE",
            "/api/v3/order",
            {"symbol": symbol, "orderId": order_id},
        )
        if not isinstance(payload, Mapping):
            raise BinanceSpotTestnetError("cancel order response was not an object")
        status = str(payload.get("status", "")).upper()
        return status in TERMINAL_CANCEL_STATUSES

    def list_open_positions(self, instrument_id: str) -> Sequence[OpenPosition]:
        symbol = _instrument_to_symbol(instrument_id)
        base_asset, _ = self._assets_for_symbol(symbol)
        account = self._account_payload()
        balance = _balance_for_asset(account, base_asset)
        if balance is None:
            return ()
        quantity = balance.free + balance.locked
        if quantity <= 0:
            return ()
        return (
            OpenPosition(
                instrument_id=instrument_id,
                side="LONG",
                quantity=quantity,
            ),
        )

    def submit_reduce_only_market_order(
        self,
        *,
        instrument_id: str,
        side: str,
        quantity: Decimal,
        client_order_id: str,
    ) -> str:
        symbol = _instrument_to_symbol(instrument_id)
        if side.upper() != "SELL":
            raise BinanceSpotTestnetError(
                "spot_reduce_only_short_unsupported:"
                "Binance Spot cash accounts can only reduce long inventory"
            )
        if quantity <= 0:
            raise BinanceSpotTestnetError("market close quantity must be positive")
        payload = self._signed_request(
            "POST",
            "/api/v3/order",
            {
                "symbol": symbol,
                "side": "SELL",
                "type": "MARKET",
                "quantity": _decimal_to_binance(quantity),
                "newClientOrderId": client_order_id,
                "newOrderRespType": "FULL",
            },
        )
        if not isinstance(payload, Mapping):
            raise BinanceSpotTestnetError("new order response was not an object")
        order_id = payload.get("orderId")
        if order_id is None:
            raise BinanceSpotTestnetError("new order response missing orderId")
        return str(order_id)

    def query_order(self, *, order_id: str, instrument_id: str) -> OrderSnapshot:
        symbol = _instrument_to_symbol(instrument_id)
        payload = self._signed_request(
            "GET",
            "/api/v3/order",
            {"symbol": symbol, "orderId": order_id},
        )
        if not isinstance(payload, Mapping):
            raise BinanceSpotTestnetError("query order response was not an object")
        return _order_snapshot_from_payload(instrument_id, payload)

    def get_account_snapshot(self) -> AccountSnapshot:
        account = self._account_payload()
        balances = tuple(
            AccountBalance(
                asset=str(row.get("asset", "")),
                free=_decimal(row.get("free", "0")),
                locked=_decimal(row.get("locked", "0")),
            )
            for row in account.get("balances", [])
            if isinstance(row, Mapping)
        )
        return AccountSnapshot(
            account_id=self._config.account_id,
            fetched_at=_iso_ms_utc(datetime.now(UTC)),
            balances=balances,
        )

    def _account_payload(self) -> Mapping[str, Any]:
        payload = self._signed_request("GET", "/api/v3/account", {})
        if not isinstance(payload, Mapping):
            raise BinanceSpotTestnetError("account response was not an object")
        return payload

    def _assets_for_symbol(self, symbol: str) -> tuple[str, str]:
        cached = self._symbol_assets.get(symbol)
        if cached is not None:
            return cached
        payload = self._unsigned_request(
            "GET",
            "/api/v3/exchangeInfo",
            {"symbol": symbol},
        )
        if not isinstance(payload, Mapping):
            raise BinanceSpotTestnetError("exchangeInfo response was not an object")
        symbols = payload.get("symbols")
        if not isinstance(symbols, list) or not symbols:
            raise BinanceSpotTestnetError(f"exchangeInfo missing symbol {symbol}")
        row = symbols[0]
        if not isinstance(row, Mapping):
            raise BinanceSpotTestnetError("exchangeInfo symbol row was not an object")
        base = row.get("baseAsset")
        quote = row.get("quoteAsset")
        if not base or not quote:
            raise BinanceSpotTestnetError(f"exchangeInfo missing assets for {symbol}")
        assets = (str(base), str(quote))
        self._symbol_assets[symbol] = assets
        return assets

    def _unsigned_request(
        self,
        method: str,
        path: str,
        params: Mapping[str, object],
    ) -> Any:
        query = urllib.parse.urlencode(params)
        url = f"{self._config.base_url}{path}"
        if query:
            url = f"{url}?{query}"
        return self._transport(
            method,
            url,
            {},
            None,
            self._config.timeout_seconds,
        )

    def _signed_request(
        self,
        method: str,
        path: str,
        params: Mapping[str, object],
    ) -> Any:
        signed_params: dict[str, object] = dict(params)
        signed_params["recvWindow"] = self._config.recv_window_ms
        signed_params["timestamp"] = self._clock_ms()
        payload = urllib.parse.urlencode(signed_params)
        signature = ed25519_signature(self._ed25519_key, payload)
        signed_params["signature"] = signature
        query = urllib.parse.urlencode(signed_params)
        url = f"{self._config.base_url}{path}?{query}"
        headers = {"X-MBX-APIKEY": self._credentials.api_key}
        return self._transport(
            method,
            url,
            headers,
            None,
            self._config.timeout_seconds,
        )


def build_binance_spot_testnet_exchange(
    settings: EmergencyFlattenSettings,
    *,
    env: Mapping[str, str] | None = None,
    transport: JsonTransport | None = None,
    clock_ms: ClockMsFn | None = None,
) -> BinanceSpotTestnetExchangeClient:
    if settings.kind != "testnet":
        raise FlattenValidationError(
            "exchange_driver_unavailable",
            "only --kind testnet is wired to the Binance Spot testnet driver",
        )
    credentials = BinanceSpotTestnetCredentials.from_env(env)
    return BinanceSpotTestnetExchangeClient(
        credentials=credentials,
        transport=transport,
        clock_ms=clock_ms,
    )


def _urllib_json_transport(
    method: str,
    url: str,
    headers: Mapping[str, str],
    data: bytes | None,
    timeout_seconds: float,
) -> Any:
    request = urllib.request.Request(
        url,
        data=data,
        headers=dict(headers),
        method=method,
    )
    try:
        with urllib.request.urlopen(request, timeout=timeout_seconds) as response:  # noqa: S310
            body = response.read()
    except urllib.error.HTTPError as exc:
        body = exc.read()
        code, msg = _error_payload(body)
        raise BinanceSpotTestnetRestError(
            status_code=exc.code,
            code=code,
            msg=msg,
        ) from exc
    except urllib.error.URLError as exc:
        reason = getattr(exc, "reason", exc)
        raise BinanceSpotTestnetError(f"binance_testnet_url_error:{reason}") from exc

    if not body:
        return {}
    try:
        return json.loads(body.decode("utf-8"))
    except json.JSONDecodeError as exc:
        raise BinanceSpotTestnetError("binance_testnet_invalid_json_response") from exc


def _error_payload(body: bytes) -> tuple[int | None, str]:
    try:
        payload = json.loads(body.decode("utf-8"))
    except json.JSONDecodeError:
        return None, "<non-json response>"
    code = payload.get("code") if isinstance(payload, Mapping) else None
    msg = payload.get("msg") if isinstance(payload, Mapping) else None
    return (int(code) if isinstance(code, int) else None, str(msg or "<missing msg>"))


def _open_order_from_payload(instrument_id: str, row: Mapping[str, Any]) -> OpenOrder:
    original_qty = _decimal(row.get("origQty", "0"))
    executed_qty = _decimal(row.get("executedQty", "0"))
    remaining = original_qty - executed_qty
    if remaining < 0:
        remaining = original_qty
    submitted_at = _ms_to_iso(row.get("time") or row.get("updateTime"))
    return OpenOrder(
        order_id=str(row["orderId"]),
        instrument_id=instrument_id,
        side=str(row["side"]).upper(),
        quantity=remaining,
        submitted_at=submitted_at,
    )


def _order_snapshot_from_payload(
    instrument_id: str,
    payload: Mapping[str, Any],
) -> OrderSnapshot:
    filled = _decimal(payload.get("executedQty", "0"))
    quote_qty = _decimal(payload.get("cummulativeQuoteQty", "0"))
    avg_price = None
    if filled > 0 and quote_qty > 0:
        avg_price = quote_qty / filled
    return OrderSnapshot(
        order_id=str(payload["orderId"]),
        instrument_id=instrument_id,
        status=str(payload.get("status", "")).upper(),
        filled_quantity=filled,
        avg_price=avg_price,
    )


def _balance_for_asset(
    account: Mapping[str, Any], asset: str
) -> AccountBalance | None:
    balances = account.get("balances", [])
    if not isinstance(balances, list):
        return None
    for row in balances:
        if not isinstance(row, Mapping):
            continue
        if row.get("asset") != asset:
            continue
        return AccountBalance(
            asset=asset,
            free=_decimal(row.get("free", "0")),
            locked=_decimal(row.get("locked", "0")),
        )
    return None


def _instrument_to_symbol(instrument_id: str) -> str:
    if not instrument_id.endswith(BINANCE_VENUE_SUFFIX):
        raise FlattenValidationError(
            "instrument_venue_not_binance",
            f"Binance Spot testnet driver requires *.BINANCE, got {instrument_id!r}",
        )
    symbol = instrument_id[: -len(BINANCE_VENUE_SUFFIX)]
    if not symbol:
        raise FlattenValidationError(
            "invalid_instrument_id",
            f"invalid Binance instrument id {instrument_id!r}",
        )
    return symbol


def _decimal(value: object) -> Decimal:
    try:
        return Decimal(str(value))
    except (InvalidOperation, ValueError) as exc:
        raise BinanceSpotTestnetError(f"invalid_decimal:{value!r}") from exc


def _decimal_to_binance(value: Decimal) -> str:
    text = format(value, "f")
    if "." in text:
        text = text.rstrip("0").rstrip(".")
    return text or "0"


def _ms_to_iso(value: object) -> str | None:
    if value is None:
        return None
    try:
        millis = int(value)
    except (TypeError, ValueError):
        return None
    dt = datetime.fromtimestamp(millis / 1000, tz=UTC)
    return _iso_ms_utc(dt)


def _iso_ms_utc(dt: datetime) -> str:
    aware = dt.astimezone(UTC)
    return aware.strftime("%Y-%m-%dT%H:%M:%S.") + f"{aware.microsecond // 1000:03d}Z"


def _system_clock_ms() -> int:
    return int(time.time() * 1000)


__all__ = [
    "BinanceSpotTestnetConfig",
    "BinanceSpotTestnetCredentials",
    "BinanceSpotTestnetError",
    "BinanceSpotTestnetExchangeClient",
    "BinanceSpotTestnetRestError",
    "build_binance_spot_testnet_exchange",
]
